# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.api.grpc.services.shopify_service_pb2 as shopify__service__pb2


class ShopifyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShopInfo = channel.unary_unary(
                '/shopify.ShopifyService/GetShopInfo',
                request_serializer=shopify__service__pb2.GetShopInfoRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.GetShopInfoResponse.FromString,
                )
        self.GetToken = channel.unary_unary(
                '/shopify.ShopifyService/GetToken',
                request_serializer=shopify__service__pb2.GetTokenRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.GetTokenResponse.FromString,
                )
        self.GetProducts = channel.unary_unary(
                '/shopify.ShopifyService/GetProducts',
                request_serializer=shopify__service__pb2.GetProductsRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.GetProductsResponse.FromString,
                )
        self.GetOrder = channel.unary_unary(
                '/shopify.ShopifyService/GetOrder',
                request_serializer=shopify__service__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.GetOrderResponse.FromString,
                )
        self.GetCollection = channel.unary_unary(
                '/shopify.ShopifyService/GetCollection',
                request_serializer=shopify__service__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.GetCollectionResponse.FromString,
                )
        self.IsActive = channel.unary_unary(
                '/shopify.ShopifyService/IsActive',
                request_serializer=shopify__service__pb2.IsActiveRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.IsActiveResponse.FromString,
                )
        self.SearchProduct = channel.unary_unary(
                '/shopify.ShopifyService/SearchProduct',
                request_serializer=shopify__service__pb2.SearchProductRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.SearchProductResponse.FromString,
                )
        self.UpdateProduct = channel.unary_unary(
                '/shopify.ShopifyService/UpdateProduct',
                request_serializer=shopify__service__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.UpdateProductResponse.FromString,
                )
        self.UpdateCollection = channel.unary_unary(
                '/shopify.ShopifyService/UpdateCollection',
                request_serializer=shopify__service__pb2.UpdateCollectionRequest.SerializeToString,
                response_deserializer=shopify__service__pb2.UpdateCollectionResponse.FromString,
                )


class ShopifyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShopInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsActive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCollection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShopifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShopInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShopInfo,
                    request_deserializer=shopify__service__pb2.GetShopInfoRequest.FromString,
                    response_serializer=shopify__service__pb2.GetShopInfoResponse.SerializeToString,
            ),
            'GetToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetToken,
                    request_deserializer=shopify__service__pb2.GetTokenRequest.FromString,
                    response_serializer=shopify__service__pb2.GetTokenResponse.SerializeToString,
            ),
            'GetProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducts,
                    request_deserializer=shopify__service__pb2.GetProductsRequest.FromString,
                    response_serializer=shopify__service__pb2.GetProductsResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=shopify__service__pb2.GetOrderRequest.FromString,
                    response_serializer=shopify__service__pb2.GetOrderResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=shopify__service__pb2.GetCollectionRequest.FromString,
                    response_serializer=shopify__service__pb2.GetCollectionResponse.SerializeToString,
            ),
            'IsActive': grpc.unary_unary_rpc_method_handler(
                    servicer.IsActive,
                    request_deserializer=shopify__service__pb2.IsActiveRequest.FromString,
                    response_serializer=shopify__service__pb2.IsActiveResponse.SerializeToString,
            ),
            'SearchProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProduct,
                    request_deserializer=shopify__service__pb2.SearchProductRequest.FromString,
                    response_serializer=shopify__service__pb2.SearchProductResponse.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=shopify__service__pb2.UpdateProductRequest.FromString,
                    response_serializer=shopify__service__pb2.UpdateProductResponse.SerializeToString,
            ),
            'UpdateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCollection,
                    request_deserializer=shopify__service__pb2.UpdateCollectionRequest.FromString,
                    response_serializer=shopify__service__pb2.UpdateCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shopify.ShopifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShopifyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShopInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/GetShopInfo',
            shopify__service__pb2.GetShopInfoRequest.SerializeToString,
            shopify__service__pb2.GetShopInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/GetToken',
            shopify__service__pb2.GetTokenRequest.SerializeToString,
            shopify__service__pb2.GetTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/GetProducts',
            shopify__service__pb2.GetProductsRequest.SerializeToString,
            shopify__service__pb2.GetProductsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/GetOrder',
            shopify__service__pb2.GetOrderRequest.SerializeToString,
            shopify__service__pb2.GetOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/GetCollection',
            shopify__service__pb2.GetCollectionRequest.SerializeToString,
            shopify__service__pb2.GetCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsActive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/IsActive',
            shopify__service__pb2.IsActiveRequest.SerializeToString,
            shopify__service__pb2.IsActiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/SearchProduct',
            shopify__service__pb2.SearchProductRequest.SerializeToString,
            shopify__service__pb2.SearchProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/UpdateProduct',
            shopify__service__pb2.UpdateProductRequest.SerializeToString,
            shopify__service__pb2.UpdateProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shopify.ShopifyService/UpdateCollection',
            shopify__service__pb2.UpdateCollectionRequest.SerializeToString,
            shopify__service__pb2.UpdateCollectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
